# App-of-Apps pattern: ArgoCD Application that watches the appsets folder
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-appsets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/JulianDerksOrg/xebia-demo-appsets-kube-live.git
    targetRevision: main
    path: appsets
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
